Repository raspibolt/raspibolt, pull requests merged in 2021-12, with the labels that each got.

#807 bonus: boot from microsd card
  bonus/raspberry-pi/boot-from-microsd-card.md
  bonus/raspberry-pi/index.md
  operating-system.md
  system-configuration.md
Labels: enhancement

#812 lnd: give user 'admin' access to lncli
  lnd.md
Labels: enhancement

#811 Update lntop bonus guide for RaspiBolt v3
  bonus/lightning/lntop.md
Labels: bug

#817 Recognize Markdown as language in repo
  .gitattributes
Labels: enhancement

#816 Add passwords [D] & [E] for Explorer and RTL
  btcrpcexplorer.md
  preparations.md
  rtl.md
Labels: enhancement

#810 Recommend optional DIY steel backup for LND 24 words
  lnd.md
Labels: enhancement

#821 lntop: update to v0.2.0
  bonus/lightning/lntop.md
Labels: application-update

#825 Add section on how to use lntop
  bonus/lightning/lntop.md
Labels: enhancement

#829 BTC RPC Explorer: update to v3.3.0
  btcrpcexplorer.md
Labels: bug, application-update

#831 Fixed typo in /etc/fstab
  bonus/raspberry-pi/boot-from-microsd-card.md
Labels: bug

#827 Bonus guide: Download the Bitcoin white paper directly from your own blockchain
  bonus/bitcoin/index.md
  bonus/bitcoin/white-paper.md
  images/paper-pink.png
  images/white-paper-transac.png
Labels: New bonus guide

#835 White paper bonus guide: Fix a few typos & update headings
  bonus/bitcoin/white-paper.md
Labels: bug

#837 Add 'Not tested v3' labels to untested legacy bonus guides + introducing labels in 'Bonus Section' index page
  bonus/bitcoin/electrum-personal-server.md.md
  bonus/bitcoin/specter-desktop.md
  bonus/index.md
  bonus/lightning/additional-scripts.md
  bonus/lightning/auto-unlock.md
  bonus/lightning/remote-lncli.md
  bonus/lightning/static-backup-dropbox.md
  bonus/lightning/zap-ios.md
  bonus/lightning/zap.md
  bonus/lightning/zeus-over-tor.md
  bonus/raspberry-pi/command-line.md
  bonus/raspberry-pi/odroid-setup.md
  bonus/raspberry-pi/system-overview.md
  bonus/raspberry-pi/trezor-agent.md
  bonus/raspberry-pi/upgrade-external-drive.md
Labels: enhancement

#842 Fix #793: Add screenshot to show symlinks colour in LND guide?
  images/lnd-symlink-colour.png
  lnd.md
Labels: enhancement

#818 Bonus guide: Balance of Satoshis
  bonus/lightning/balance-of-satoshis.md
  bonus/lightning/index.md
  images/bonus-bos-graph.png
  images/bos-bot.png
  images/bos-illustration.png
Labels: New bonus guide

#845 Fix circular rebalancing picture broken link in Balance of Satoshis guide
  bonus/lightning/balance-of-satoshis.md
  images/circular-rebalancing-lnbook.png
Labels: bug

#852 system overview: re-add netcat
  bonus/raspberry-pi/system-overview.md
Labels: bug
