Repository raspibolt/raspibolt, pull requests merged in 2022-01, with the labels that each got.

#872 Fix RTL broken link
  rtl.md
Labels: bug

#876 Removed outdated reference in Electrs guide about deactivated Bitcoin Core wallet
  electrs.md
Labels: bug

#871 Fix small typo in Bitcoin Core guide
  bitcoin-core.md
Labels: wording

#874 Update Electrs to v0.9.4
  electrs.md
Labels: application-update

#869 Update rtl.md
  rtl.md
Labels: bug

#893 Change to Node.js v16 and spelling standardization
  bonus/lightning/balance-of-satoshis.md
  btcrpcexplorer.md
  rtl.md
Labels: application-update
