Repository raspibolt/raspibolt, pull requests merged in 2022-09, with the labels that each got.

#1084 Adds checksum timestamp check to Bitcoin Core installation steps
  guide/bitcoin/bitcoin-client.md
  images/bitcoin-ots-check.PNG
Labels: enhancement

#1076 [UPDATE BONUS GUIDE] Minor update of the Fulcrum bonus guide
  guide/bonus/bitcoin/fulcrum.md
Labels: enhancement

#1079 Update RTL guide to v0.13.1 + use "--omit=dev" flag + a few formating bug fixes
  guide/lightning/web-app.md
Labels: application-update

#1089 Push remote LND static channel backups to GitHub via Tor
  guide/lightning/channel-backup.md
Labels: enhancement

#1068 Make a Lightning payment. Fix LNURL pay section with lncli command
  guide/lightning/lightning-client.md
Labels: bug

#1093 Fixes two typos in LND "Open a channel" section
  guide/lightning/lightning-client.md
Labels: bug

#1088 Add missing separator + rewording of Safu Ninja blurb
  guide/bonus/bitcoin/index.md
Labels: bug

#1094 CLN: fix building and installation instructions
  guide/bonus/lightning/cln.md
Labels: bug
