Repository raspibolt/raspibolt, pull requests merged in 2022-10, with the labels that each got.

#1108 Add a "Secure your home network and devices" section to the "Preparations" chapter
  guide/raspberry-pi/preparations.md
Labels: enhancement

#1100 Fixes typo in rebalancing command + small rewording of explanations
  guide/bonus/lightning/balance-of-satoshis.md
Labels: bug

#1083 Update LND to v0.15.2 (URGENT - hot fix)
  guide/lightning/lightning-client.md
Labels: application-update

#1109 [UPDATE] Update privacy section to enable official Tor Package Repository
  guide/raspberry-pi/privacy.md
Labels: enhancement

#1119 Adds an Uninstall section to the LNBits bonus guide
  guide/bonus/lightning/lnbits.md
Labels: enhancement

#1097 [UPDATE BONUS GUIDE] Fulcrum
  guide/bonus/bitcoin/fulcrum.md
Labels: New bonus guide

#1123 [UPDATE BONUS GUIDE] Electrum Wallet guide updated to Raspibolt v3 & other fixes
  guide/bonus/bitcoin/electrum-wallet-desktop.md
  guide/bonus/bitcoin/electrum.md
  guide/bonus/bitcoin/index.md
  images/50_electrum_wallet_local.png
  images/50_electrum_wallet_tor.png
  images/electrum-wallet-local.PNG
  images/electrum-wallet-tor-check.PNG
  images/electrum-wallet-tor.png
  images/electrum-win-shortcut-local.PNG
  images/electrum-win-shortcut-tor.PNG
  images/electrum_wallet_logo.png
Labels: application-update

#1120 Update Lightning Terminal to v0.8.1 (contains the LND v0.15.2 hotfix)
  guide/bonus/lightning/lightning-terminal.md
Labels: application-update

#1134 [NEW BONUS GUIDE] regolancer
  guide/bonus/lightning/index.md
  guide/bonus/lightning/regolancer.md
Labels: New bonus guide

#1025 CLN: c-lightning-Rest & RTL configuration
  guide/bonus/lightning/cln.md
Labels: enhancement, cln

#1142 [BUGFIX] prevent port collision on macaroon creation
  guide/bonus/lightning/cln.md
Labels: bug

#1121 Update mempool.md
  guide/bonus/bitcoin/mempool.md
Labels: enhancement
