Repository raspibolt/raspibolt, pull requests merged in 2022-12, with the labels that each got.

#1162 Improve the Upgrade section of the regolancer bonus guide
  guide/bonus/lightning/regolancer.md
Labels: enhancement

#1199 [UPDATE BONUS GUIDE] lnd-v0.15.5
  guide/lightning/lightning-client.md
Labels: enhancement, core guide maintenance

#1191 Bitcoin guide update to 24.0.1 with OTS verification & OTS installation fix
  guide/bitcoin/bitcoin-client.md
Labels: application-update
