Repository raspibolt/raspibolt, pull requests merged in 2022-02, with the labels that each got.

#897 electrs: fix update instructions
  electrs.md
Labels: bug

#900 Remove qrencode package installation from core guide as not used
  system-configuration.md
Labels: bug

#901 Fixed path to RTL sample config file
  rtl.md
Labels: bug

#902 Updated list of default packages to install
  bonus/bitcoin/white-paper.md
  bonus/lightning/additional-scripts.md
  system-configuration.md
Labels: enhancement

#870 Bonus guide: Mempool
  bonus/bitcoin/index.md
  bonus/bitcoin/mempool.md
  images/mempool.png
Labels: New bonus guide

#906 Small changes for Pi Imager guidelines
  operating-system.md
Labels: bug

#912 move tor-config for user bitcoin
  bitcoin-core.md
  privacy.md
Labels: bug

#828 Bonus guide: Circuit Breaker
  bonus/lightning/circuit-breaker.md
  bonus/lightning/index.md
  images/circuit-breaker-tweet.png
Labels: New bonus guide

#936 Add keysend option in lnd.conf
  lnd.md
Labels: feature request

#934 Update lntop to v0.3.0 + new Update & Uninstall sections
  bonus/lightning/lntop.md
Labels: application-update

#939 Add a favicon to raspibolt.org
  favicon.ico
Labels: enhancement

#932 Updates the Zap desktop bonus guide to v3
  bonus/lightning/index.md
  bonus/lightning/zap-desktop.md
  bonus/lightning/zap.md
  images/zap-desktop.png
Labels: bug

#830 Bonus guide: rebalance-lnd
  bonus/lightning/rebalance-lnd.md
  images/rebalance-lnd-illustration.png
Labels: New bonus guide

#943 Add missing entry for "rebalance-lnd" in the lightning bonus guide index
  bonus/lightning/index.md
Labels: bug
