Repository raspibolt/raspibolt, pull requests merged in 2023-11, with the labels that each got.

#1377 [UPDATE] Bump LND to v0.17.1
  guide/lightning/lightning-client.md
Labels: application-update

#1378 [UPDATE] Bump version Fulcrum and rebuilt checks according to dev changes
  guide/bonus/bitcoin/fulcrum.md
Labels: application-update

#1379 web-app: fix enumeration and formatting
  guide/lightning/web-app.md
Labels: wording

#1380 [UPDATE] Bump LND to v0.17.2
  guide/lightning/lightning-client.md
Labels: application-update

#1381 [UPDATE] Bump version Fulcrum and small fix
  guide/bonus/bitcoin/fulcrum.md
Labels: bug, application-update

#1383 [UPDATE BONUS GUIDE] Update Sparrow CLI (versioning)
  guide/bonus/bitcoin/sparrow-terminal.md
Labels: application-update
