Repository raspibolt/raspibolt, pull requests merged in 2023-06, with the labels that each got.

#1293 Update LND guide to v0.16.3
  guide/lightning/lightning-client.md
Labels: core guide maintenance

#1297 [UPDATE] BTC RPC Explorer to v3.40 + add variable $VERSION
  guide/bitcoin/blockchain-explorer.md
Labels: application-update

#1200 [GENERAL UPDATE] Add variables $VERSION to agility the installing and updating process of the services
  guide/bitcoin/bitcoin-client.md
  guide/lightning/lightning-client.md
Labels: future upgrade, feature request
