Repository raspibolt/raspibolt, pull requests merged in 2023-01, with the labels that each got.

#1156 [UPDATE BONUS GUIDE] Refresh and test for V3 of the BitBoxApp guide
  guide/bonus/bitcoin/bitboxapp.md
  images/bitboxapp_success.png
  images/bitboxapp_tor_success.png
  images/electrum_BitBoxApp.png
Labels: enhancement, application-update

#1185 [NEW BONUS GUIDE] JoinMarket-webui (Jam)
  guide/bonus/bitcoin/Jam.md
  guide/bonus/bitcoin/index.md
Labels: new bonus guide

#1225 [update guide] electrs v0.9.11
  guide/bitcoin/electrum-server.md
Labels: application-update

#1204 Update lightning-client.md
  guide/lightning/lightning-client.md
Labels: feature request

#1220 [UPDATE BONUS GUIDE] Push RTL to v0.13.4
  guide/lightning/web-app.md
Labels: application-update

#1195 [UPDATE BONUS GUIDE] LNDg - v1.5.0
  guide/bonus/lightning/lndg.md
Labels: enhancement, future upgrade, application-update

#1104 [UPDATE BONUS GUIDE] Improved I2P bonus guide, standardizing the format and restructuring steps to clarify the guide
  guide/bonus/bitcoin/i2p.md
Labels: enhancement

#1207 [UPDATE BONUS GUIDE] Sparrow Terminal: Add mixing section
  guide/bonus/bitcoin/sparrow-terminal.md
Labels: application-update
